[[ $- != *i* ]] && return

DEFAULT="\e[39;0m"
DEFAULT_BOLD="\e[39;1m"

RED="\e[31;1m"
GREEN="\e[32;1m"
YELLOW="\e[33;1m"

alias ls="ls --color"
export PATH="$PATH:$HOME/.tools"

PS1="\[$YELLOW\] \[$GREEN\]\u\[$DEFAULT_BOLD\]@\[$RED\]\h\[$DEFAULT_BOLD\] \W\[$YELLOW\] \[$DEFAULT\]   "
