[[ $- != *i* ]] && return

DEFAULT="\e[39;0m"
DEFAULT_BOLD="\e[39;1m"

RED="\e[31;1m"
GREEN="\e[32;1m"
YELLOW="\e[33;1m"

alias vim="nvim"
alias ls="ls --color"
alias update="sudo pacman -Syu --noconfirm && clear && figlet Upgrade Done ! | lolcat"

PS2="\[$GREEN\]  \[$DEFAULT\]"

PS1="\[$YELLOW\] \[$GREEN\]\u\[$DEFAULT_BOLD\]@\[$RED\]\h\[$DEFAULT_BOLD\] \W\[$YELLOW\] \[$DEFAULT\]   "
