#!/bin/bash

sxhkd &

bspc monitor -s 1 2 3 4 5 6 7 8 9

bspc config border_width 2
bspc config window_gap 17

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
