syntax on

set bg=light
set tabstop=4
set encoding=utf-8

set title
set number
set nowrap
set wildmenu
set hlsearch
set incsearch
set showmatch
set autoindent
set noswapfile

highlight Normal        ctermbg=234

highlight Number        ctermfg=yellow

highlight Boolean       ctermfg=yellow         cterm=italic

highlight Comment       ctermfg=gray           cterm=italic

highlight Function      ctermfg=cyan

highlight PreProc       ctermfg=magenta        cterm=bold

highlight String        ctermfg=green
highlight Character     ctermfg=red            cterm=bold

highlight Type          ctermfg=blue           cterm=italic
highlight Structure     ctermfg=blue           cterm=bold

highlight Label         ctermfg=darkgreen      cterm=bold
highlight Repeat        ctermfg=lightgreen     cterm=italic
highlight Conditional   ctermfg=lightgreen     cterm=italic

highlight Todo          ctermbg=yellow         cterm=bold
highlight Error         ctermbg=red            cterm=bold
highlight Special       ctermfg=magenta        cterm=italic
